pre-commit:
  parallel: true
  commands:
    prettier:
      run: aube dlx prettier --ignore-unknown --write {staged_files}
      stage_fixed: true
    check:
      run: aube dlx @biomejs/biome check --write --no-errors-on-unmatched --files-ignore-unknown=true --colors=off {staged_files}
      stage_fixed: true
