const Icons: Record<string, string> = {
	"Apache Airflow (MWAA)": "simple-icons:apacheairflow",
	"Azure DevOps": "codicon:azure-devops",
	"Azure Pipelines": "codicon:azure-devops",
	"Burp Suite": "simple-icons:burpsuite",
	"C++": "simple-icons:cplusplus",
	".NET/C#": "simple-icons:dotnet",
	"Elastic Kubernetes Service": "simple-icons:amazonaws",
	Bamboo: "simple-icons:bamboo",
	Certificate: "charm:certificate",
	Cognito: "simple-icons:amazonaws",
	CSS: "simple-icons:css3",
	Docker: "simple-icons:docker",
	DynamoDB: "simple-icons:amazondynamodb",
	Email: "charm:mail",
	Folder: "codicon:folder",
	Git: "simple-icons:git",
	GitHub: "simple-icons:github",
	Globe: "charm:globe",
	Graduate: "charm:graduate-cap",
	HTML: "simple-icons:html5",
	JavaScript: "simple-icons:javascript",
	Jenkins: "simple-icons:jenkins",
	Kinesis: "simple-icons:amazonaws",
	Kubeflow: "simple-icons:kubernetes",
	Link: "charm:link-external",
	LinkedIn: "simple-icons:linkedin",
	Metasploit: "simple-icons:metasploit",
	MLflow: "simple-icons:mlflow",
	Next: "simple-icons:nextdotjs",
	Node: "simple-icons:nodedotjs",
	PostgreSQL: "simple-icons:postgresql",
	Python: "simple-icons:python",
	React: "simple-icons:react",
	Redshift: "simple-icons:amazonaws",
	Splunk: "simple-icons:splunk",
	SQS: "simple-icons:amazonaws",
	Tailwind: "simple-icons:tailwindcss",
	ThemeSwitch: "lucide:sun-moon",
	TypeScript: "simple-icons:typescript",
};

export default Icons;
